/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    MediaItem: typeof import('./src/components/MediaItem.vue')['default']
    MiniPlayer: typeof import('./src/components/MiniPlayer.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    Player: typeof import('./src/components/Player.vue')['default']
    PlayerControllerButton: typeof import('./src/components/PlayerControllerButton.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
