/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    LibraryItem: typeof import('./src/components/LibraryItem.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    Player: typeof import('./src/components/Player.vue')['default']
    PlayerControllerButton: typeof import('./src/components/PlayerControllerButton.vue')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TagImage: typeof import('./src/components/TagImage.vue')['default']
    Unit8ArrayImage: typeof import('./src/components/Unit8ArrayImage.vue')['default']
  }
}
